---
version: '2.1'

services:
    web:
      image: nginx:1.16
      restart: always
      volumes:
       - ./conf.d:/etc/nginx/conf.d/
      network_mode: host
      environment:
       - NGINX_HOST=cbeta.tripitakas.net
       - NGINX_PORT=80
      #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
