version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    environment:
      - DOZZLE_TAILSIZE=100
      - DOZZLE_FILTER=name=web_1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8005:8080
